### ISSUE TITLE
Para Birimleri sorunu

### ISSUE THREAD

**Issue by k1meister** [kgns/paymes-whmcs#1]
EUR ile yapilan ödemeleri Türk Lirasına çeviriyor ve yanlış bilgiler geliyor.

Örnek:

10 EUR Invoice ödüyor müşteri
95 euro ödemis gibi gösteriyor ve müşteriye 85 euro credit balance ekliyor.

**Comment by hermesthecat** [comment]
hemen hemen Türk ödeme aracı firma eklentilerin hepsinda var bu sorun.
kimsenin aklına gelmemiş herhalde.
dünden beridir bende bu sorun ile uğraşıyorum.

callback dosyası içerisinde müşterinin para birimi değerini çekerek gelen tutarı ona göre işleme sokmamız gerekiyor.

**Comment by k1meister** [comment]
Dünden beri uğrasıyorum, eğer cözümünü bulursam paylaşırım.

**Comment by hermesthecat** [comment]
https://github.com/abazad/paymes-whmcs/commit/e8ad9f4230783ed19f8c9a93192c3327eee06152

şeklinde bir düzenleme yaptim hocam lakin benim api başvurum henüz onaylanmadığı için test edemedim :/

**Comment by k1meister** [comment]
@abazad Tesekkür ederim. Çalıştı, büyük bir sorundan kurtardın beni 👍  Burayı yinede açık bırakıyorum belki @kgns opsiyonel olarak eklemek ister.

**Comment by hermesthecat** [comment]
rica ederim hocam.
